config/routes.rb
Rails.application.routes.draw do
  resources :profiles
	devise_for :users, controllers: {
		users: 'users/registrations'
		# sessions: 'users/sessions'
	}
	resources :posts
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, optional: true
	validates_presence_of :created_at, :text
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable
				 
	validates_presence_of :first_name, :last_name
	
	def full_name
		"#{first_name} #{last_name}"
	end

	def list_name
		"#{last_name.upcase}, #{first_name.upcase}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# Do this method before the actions 'show', 'edit', and 'update'
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	# The view for making a new post.
	def new
		@post = Post.new
	end

	# Actually make the post 
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id # current_user is given to us from devise
		if @post.save
			# Redirect to the show page for Post.  And pass along this cool (useless...) notice
			redirect_to @post, notice: 'Your post was created successfully'
		else
			render :new
		end
	end

	def edit;	end

	def update
		if @post.update(post_params)
			redirect_to @post, notice: 'Your post was updated successfully'
		else 
			render :edit
		end
	end

	def show;	end

	def destroy
		@post.delete
		redirect_to posts_path, notice: 'Your post was delete successfully'
	end

	private

		def post_params
			params.require(:post).permit(:created_at, :text)
		end

		# This is called in a before action at the top of this file
		def set_post
			@post = Post.find(params[:id])
		end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def homepage
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
	def new
		Rails.logger.dev "HEY"
    super
  end


	def index
		@users = User.all
	end

  # POST /resource
  def create

		# When the form is submitted, we get it's id in params.
		@user ||= User.new(params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation))
		@user.user_id = current_user.id # current_user is given to us from devise
		if @user.save
			# Redirect to the show page for Post.  And pass along this cool (useless...) notice
			redirect_to @user, notice: 'Your user was created successfully'
		else
			render :new
		end

		super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

	# protected
	
  # If you have extra params to permit, append them to the sanitizer.
	def configure_sign_up_params
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password, :password_confirmation])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
		"active" if current_page?(path)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Nati</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
 <body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<%= render 'shared/nav'%>
    			<%= yield %>
				</div>
			</div>
		</div>
 </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.date_field :created_at %>
	<%= f.text_area :text%>
	<%= f.submit 'Save' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id %>
	</td>
	<td>
		<%= post.created_at %>
	</td>
	<td>
		<%= post.user.email %>
	</td>
	<td>
		<%= truncate(post.text) %>
	</td>
	<td>
		<%# Change the id of this element to include the `post.id` %>
		<%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}" %>
	</td>
	<td>
		<%# Change the id of this element to include the `post.id`. We know to use method: :delete by looking at the routes (you'd think the post_path needed to be destroy_post) %>
		<%= link_to 'Delete', post_path(post), id: "delete_post_#{post.id}_from_index", method: :delete %>
	</td>
</tr>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Text
			</th>
			<th>
			</th>
		</tr>
	</thead>
	<tbody>
	<%# This magic works with the _posts.html.erb file.  Crazy. %>
		<%= render @posts %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<%= f.date_field :created_at %>
	<%= f.text_area :text %>
	<%= f.submit 'Save' %>
<% end %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_nav.html.erb
<div class="logo">
	<h1>Illuminati Hottie</h1>
</div>

<ul class="nav nav-tabs custom-nav">
	<li class="<%= active?(root_path)%>">
		<%= link_to "Home", root_path %>
	</li>

	<li class="<%= active?(posts_path)%>">
		<%= link_to "Posts", posts_path %>
	</li>

	<li class="<%= active?(new_post_path)%>">
		<%# We give it a very specific id %>
		<%= link_to "New", new_post_path, id: "new_post_from_nav" %>
	</li>


	<li class="<%= active?(edit_user_registration_path)%>">
		<%= link_to "Account", edit_user_registration_path %>
	</li>

	<li class="pull-right">
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	</li>
</ul>

app/views/users.bak/_user.html.erb
<tr>
	<td>
		<%= user.id %>
	</td>
	<td>
		<%= user.first_name %>
	</td>
	<td>
		<%= user.last_name %>
	</td>
	<td>
	<%= user.email %>
	</td>
</tr>

app/views/users.bak/index.html.erb
<h1>Users</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				First Name
			</th>
			<th>
				Last Name
			</th>
			<th>
				Email
			</th>
		</tr>
	</thead>
	<tbody>
	<%# This magic works with the _posts.html.erb file.  Crazy. %>
		<%= render @users %>
	</tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>